/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Basquete.glb --transform 
Files: public/models/Basquete.glb [2.07MB] > Basquete-transformed.glb [173.64KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Basquete-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.35}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['basket.002']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['basket_linha.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Basquete-transformed.glb')
