/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/EUAsoccer.glb --transform 
Files: public/models/EUAsoccer.glb [891.01KB] > EUAsoccer-transformed.glb [77.63KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/EUAsoccer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.18}>
        <mesh geometry={nodes.Sphere009.geometry} material={materials.EUAsoccer_marrom} />
        <mesh geometry={nodes.Sphere009_1.geometry} material={materials.EUAsoccer_branco} />
      </group>
    </group>
  )
}

useGLTF.preload('/EUAsoccer-transformed.glb')
