/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Futbol.glb --transform 
Files: public/models/Futbol.glb [113.77KB] > Futbol-transformed.glb [16.56KB] (85%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Futbol-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.28}>
        <mesh geometry={nodes.Icosphere001.geometry} material={materials['soccer_branco.001']} />
        <mesh geometry={nodes.Icosphere001_1.geometry} material={materials['soccer_preto.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Futbol-transformed.glb')
