/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Pickle.glb --transform 
Files: public/models/Pickle.glb [559.62KB] > Pickle-transformed.glb [64.22KB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pickle-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pickleV2.geometry} material={materials.pickle_verde} scale={0.095} />
    </group>
  )
}

useGLTF.preload('/Pickle-transformed.glb')
