/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tennis.glb --transform 
Files: public/models/tennis.glb [161.53KB] > tennis-transformed.glb [19.64KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tennis-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.084}>
        <mesh geometry={nodes.Sphere015.geometry} material={materials.tennis_linha} />
        <mesh geometry={nodes.Sphere015_1.geometry} material={materials.tennis_verde} />
      </group>
    </group>
  )
}

useGLTF.preload('/tennis-transformed.glb')
