/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Voley.glb --transform 
Files: public/models/Voley.glb [371.71KB] > Voley-transformed.glb [42.82KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Voley-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.2}>
        <mesh geometry={nodes.Cube.geometry} material={materials.volley_amarelo} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.volley_branco} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.volley_azul} />
      </group>
    </group>
  )
}

useGLTF.preload('/Voley-transformed.glb')
